### ISSUE TITLE
Spoofing User-Agent breaks PrivacyPass

### ISSUE THREAD

**Issue by concatime** [privacypass/challenge-bypass-extension#106]
Hi. On Firefox, when you install CanvasBlocker, spoofing User-Agent with `Navigator API` breaks Privacy Pass. To reproduce it, you need a non-Windows environnement witih Firefox and PrivacyPass, install CanvasBlocker and load settings from [this file](//gist.githubusercontent.com/concatime/b4edf8637020bce90b71aaf4ef12d08f/raw/settings.json).
It works when you uncheck `userAgent` under `Protected API features` and restart Firefox.

**Comment by alxdavids** [comment]
This is probably related to #99

**Comment by CrafterLaughter** [comment]
So I just ran into this on Firefox 70.0 (64-bit) on my W10 1903.  I'm using containers and have tons of privacy addons loaded.  Fortunately I only had to try disabling one because of your user agent suggestion.  I'm using the addon Random User-Agent.

I deselected "run in private windows" for that addon and fired up a private window.  Sure enough I could generate tokens that would persist when I exited "private browsing."  I still have the Random User-Agent addon loaded for normal browsing though, so I'm wondering if I won't luck out with it actually decrementing tokens?

Do you guys have a quick URL I can use to test if it successfully decrements tokens with the Random User-Agent addon still loaded?  I'm not using Tor otherwise that would have been a easy means of triggering a CAPTCHA.

**Comment by maximbaz** [comment]
I've already tried something similar, generated tokens with "real" user-agent, then browsed with "fake" user agent for months, definitely had to complete some captchas, and my counter never decreased.

**Comment by maximbaz** [comment]
I've seen some threads mentioning that `2.0.4` may have some improvements, I tested, it's still the same issue - when you click on "Get more passes" and enter captcha, if User-Agent is spoofed captcha.website returns 403, but if User-Agent is not spoofed it returns 200 and passes get assigned.

**Comment by Jookia** [comment]
This breaks if privacy.resistFingerprinting is enabled.

**Comment by FireMasterK** [comment]
The same occurs on Brave, I found the issue:
privacy pass sends the Browser's real user-agent instead of the spoofed one.
This is what privacypass sends:
![image](https://user-images.githubusercontent.com/20838718/85795234-98177a00-b755-11ea-9f07-a80122698626.png)
This is what my user agent spoofer sets it to:
![image](https://user-images.githubusercontent.com/20838718/85795356-c006dd80-b755-11ea-9b5b-896c66f470c6.png)
Could we expose the request somehow so that other extensions such as user agent spoofers could modify these too?

**Comment by FireMasterK** [comment]
https://github.com/privacypass/challenge-bypass-extension/blob/master/src/ext/issuance.js#L138-L161
I found the problematic code

**Comment by user037160** [comment]
I like to stress this issue out as it is just not working in the Tor Browser (the place where it is most needed).

**I am offering the bounty of `$45` paid in BTC/XMR/Lightning BTC** (depending on fees and your preference). The bounty will be paid upon releasing extension at addons.mozilla.org that is working in Tor Browser (it is possible to get passes on hCaptha and CloudFlare).

My big thanks to everyone who was and will be contributing to this great project to fix the broken internet. :heart:

**Comment by AliMilani** [comment]
same problem with _BP Proxy Switcher_ extension

**Comment by armfazh** [comment]
the chrome extension adverts about [Conflict Resolution](https://developer.chrome.com/docs/extensions/reference/webRequest/#conflict-resolution)
that is. when more than one extensions try to modify headers, only the last-recent installed works.

**Comment by migueldemoura** [comment]
From the [updated README](https://github.com/privacypass/challenge-bypass-extension#extensions-that-modify-user-agent-or-headers):

> There is a [conflict resolution](https://developer.chrome.com/docs/extensions/reference/webRequest/#conflict-resolution) happening when more than one extension tries to modify the headers of a request. According to documentation, the more recent installed extension is the one that can update headers, while others will fail.
> 
> Compounded to that, Cloudflare will ignore clearance cookies when the user-agent request does not match the one used when obtaining the cookie.

As for the other issues mentioned above, we support the Tor Browser and plain Firefox with `privacy.resistFingerprinting` enabled - please raise an issue if you're having issues with either!
