### ISSUE TITLE
[Probably Bug]It not bypass cloudflare of some site's images(or videos)

### ISSUE THREAD

**Issue by xfm00mm** [privacypass/challenge-bypass-extension#135]
If Cloudflared website has images(or videos) that placed other cloudflared domain,It often not bypassed.

> Example:
> https://gigazine.net/     (images is on [igzn.jp](url))
>https://animeflv.net/ver/52947/null-peta-1    (videos on [streamium.xyz](url) images on [somoskudasai.com](url))

![スクリーンショット_2019-10-27_02-19-39](https://user-images.githubusercontent.com/24968128/67623516-84f28a00-f815-11e9-914d-e41141d021ca.png)
Not bypassed domain returns 403 and breaks website layout.

```
My env:
Linux Mint 19.2 Tina 64bit
Tor 0.4.1.6-1~bionic+1
Firefox 70.0b14
Privacy pass 2.0.2
```

```
Other addons:
Ageless 1.3
AudioContext Fingerprint Defender 0.1.3
Canvas Fingerprint Defender 0.1.5
Change Timezone (Time Shift) 0.1.4
Decentraleyes 2.0.13
Don't track me Google 4.22
Firefox DevTools ADB Extension 0.0.5
Firefox Multi-Account Containers 6.1.1
h264ify 1.1.0
Nano Defender 15.0.0.167
NoScript 11.0.3
Privacy Possum 2019.7.18
Redirector 3.2.1
uBlock Origin 1.23.0
WebGL Fingerprint Defender 0.1.2

```

**Comment by alxdavids** [comment]
Hi, thanks for providing this information and these example websites. I'll do some testing and see what the issue is.

**Comment by alirezajavani** [comment]
breaks website layout.

My env: Linux Mint 19.2 Tina 64bit Tor 0.4.1.6-1~bionic+1 Firefox 70.0b14 Privacy pass 2.0.2 Other addons: Ageless 1.3 AudioContext Fingerprint Defender 0.1.3 Canvas Fingerprint Defender 0.1.5 Change Timezone (Time Shift) 0.1.4 Decentraleyes 2.0.13 Don't track me Google 4.22 Firefox DevTools ADB Extension 0.0.5 Firefox Multi-Account Containers 6.1.1 h264ify 1.1.0 Nano Defender 15.0.0.167 NoScript 11.0.3 Privacy Possum 2019.7.18 Redirector 3.2.1 uBlock Origin 1.23.0 WebGL Fingerprint Defender 0.1.2 

 

 alxdavids commented on Oct 28, 2019

Hi, thanks for providing this information and these example websites. I'll do some testing and see what the issue is.

 

 alxdavids added the investigate labelon Oct 28, 2019

WritePreview

 

Comment

Remember, contributions to this repository should follow our GitHub Community Guidelines.

Ass

**Comment by alirezajavani** [comment]
breaks website layout.

My env: Linux Mint 19.2 Tina 64bit Tor 0.4.1.6-1~bionic+1 Firefox 70.0b14 Privacy pass 2.0.2 Other addons: Ageless 1.3 AudioContext Fingerprint Defender 0.1.3 Canvas Fingerprint Defender 0.1.5 Change Timezone (Time Shift) 0.1.4 Decentraleyes 2.0.13 Don't track me Google 4.22 Firefox DevTools ADB Extension 0.0.5 Firefox Multi-Account Containers 6.1.1 h264ify 1.1.0 Nano Defender 15.0.0.167 NoScript 11.0.3 Privacy Possum 2019.7.18 Redirector 3.2.1 uBlock Origin 1.23.0 WebGL Fingerprint Defender 0.1.2 

 

 alxdavids commented on Oct 28, 2019

Hi, thanks for providing this information and these example websites. I'll do some testing and see what the issue is.

 

 alxdavids added the investigate labelon Oct 28, 2019

WritePreview

 

Comment

Remember, contributions to this repository should follow our GitHub Community Guidelines.

Ass

**Comment by ValZapod** [comment]
Cloudflare uses cookies to save the status of the user, of course when you use cookies on other domain, and of course you are not allowed by Chrome to use third-party cookies. Go to chrome://settings/cookies and check all cookies. And report.

**Comment by migueldemoura** [comment]
Only said website can fix the issue, which is also not related to Privacy Pass. They must not issue challenges for requests that are not a main navigation, i.e., the user must be able to get that challenge page to be able to solve it.
