### ISSUE TITLE
Not getting hcaptcha passes

### ISSUE THREAD

**Issue by UltraBlackLinux** [privacypass/challenge-bypass-extension#165]
Hello,
After clicking on the get more passes button, and solving the hcaptcha, i still only get the [!!!] symbol, without earning any passes...
Any suggestions?

**Comment by alxdavids** [comment]
I can confirm that this is an issue for me as well. Seems like a problem in the response from the hCaptcha Privacy Pass server. Tested in Chromium Version 79.0.3919.0 (Developer Build) (64-bit).

Issue request data & headers:

![image](https://user-images.githubusercontent.com/7470539/81391412-f096a780-9114-11ea-822b-70230ac6b054.png)

Issue response headers:

![image](https://user-images.githubusercontent.com/7470539/81391440-fee4c380-9114-11ea-972f-8090576261a1.png)

Issue response body:

```
{"challenge-bypass-tokens-error":"forbidden"}
```

@durch: Do you know what the problem is here?

**Comment by miyurusankalpa** [comment]
I am facing the issue as well can someone fix this. 

I cannot solve a hcaptacha even if I tried a million times. its so much broken. This extension is the only thing keeping me sane, by passing cloud flare captcha pages and now its not working as well.

**Comment by theg00s3** [comment]
I have the same issue. I'm on Firefox 76.0.1 on MacOS

**Comment by alxdavids** [comment]
Just to clarify of what the understanding of the issue is here: Privacy Pass works fine on the Cloudflare CAPTCHA page, it's just on native hCaptchas that it currently does not work (i.e. https://www.hcaptcha.com/privacy-pass). So the problem is not related to Cloudflare. I'll speak to hCaptcha to see what needs to be done to fix this.

**Comment by durch** [comment]
@UltraBlackLinux thank you for raising this, both token issuance and redemption should work as expected now. cc

**Comment by alxdavids** [comment]
Just tested and it works fine for me now, thanks @durch !
