### ISSUE TITLE
don't work for openai.com

### ISSUE THREAD

**Issue by EasyChris** [privacypass/challenge-bypass-extension#382]
Before reporting a new bug, verify if your request is already being tracked by another issue: https://github.com/privacypass/challenge-bypass-extension/issues.

---

If you believe that this is a new bug, please proceed to create an issue. The issue will be investigated after you have filled in the following information.

**Describe the bug**
when i visit openai.com  the website tell me some chrome extension block this web, when i try to close  privacypass extension, the web is open 

**How to reproduce**
1. Go to 'https://chat.openai.com/chat'
2. it show some chrome extension block openai.com website
3. close the privacypass then web can visit

**Expected behavior**
A description of what is expected to happen.

**System (please complete the following information):**
 - OS: [macos]
 - Cloudflare tokens 
 - Browser [brave]
 - Browser Version [1.46.134 ]
 - Privacy Pass Version [3.0.4 ]

**Comment by mcgroarty** [comment]
Same issue here. With Chrome Version 108.0.5359.124 (Official Build) (x86_64) on macOS it intermittently causes an err_blocked_by_client when loading https://chat.openai.com/chat

It doesn't reproduce every time. Perhaps it only happens when no more tokens are ready? When the issue does happen, if I disable the extension and reload the page, I  can authenticate.

**Comment by thibmeu** [comment]
We are tracking this issue in #400 as part of an upgrade to the latest IETF draft.
