### ISSUE TITLE
Cannot get hCAPTCHA passes from official page, but can elsewhere

### ISSUE THREAD

**Issue by LewsTherinTelescope** [privacypass/challenge-bypass-extension#385]
**Describe the bug**
Filling out the captcha on the [recommended demo page](https://www.hcaptcha.com/privacy-pass) doesn't give any passes.

**How to reproduce**
1. Go to [hCaptcha's Privacy Pass page](https://www.hcaptcha.com/privacy-pass).
2. Click on the CAPTCHA.
3. Fill it out.
4. Check number of passes left.

**Expected behavior**
The number of passes should have gone up by five.

**System (please complete the following information):**
 - OS: MacOS
 - Cloudflare tokens or hCaptcha tokens? hCaptcha
 - Browser: Firefox
 - Browser Version: 110.0a1
 - Privacy Pass Version: 3.0.4

**Additional context**
Filling it out on other pages (such as [this hCaptcha demo](https://accounts.hcaptcha.com/demo)) does grant them just fine. It also works fine on [the Cloudflare demo](https://captcha.website/).

**Comment by Adyel** [comment]
Can confirm. I have the same issue.

**Comment by wordlesswind** [comment]
I was able to get tokens on Microsoft Edge, but not on Google Chrome.

**Comment by liamjones** [comment]
Ditto on macOS Firefox Developer Edition 112.0b4 (64-bit) with Privacy Pass 3.0.5

**Comment by SomeHybrid** [comment]
Also have the same issue (Firefox 112.0.1 MacOS)

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
Same issue Firefox 115.0.2 on Linux , Privacy Pass Version 3.0.5. 
🔴 hCaptcha 
🟢 Cloudflare  

```
https://accounts.hcaptcha.com/demo

Verification Success!
siteverify response data:

{
    "success": true,
    "challenge_ts": "2023-07-31T01:44:03.000000Z",
    "hostname": "hcaptcha.com",
    "credit": false
}
```

**Comment by wordlesswind** [comment]
> 🔴 hCaptcha

![image](https://github.com/privacypass/challenge-bypass-extension/assets/9050713/4c20757d-08f4-43dd-be77-7ed72d369731)

This is probably due to hCaptcha changing its validation method.

But with Mozilla Firefox (115.0.3, [Microsoft Store Version](https://apps.microsoft.com/store/detail/mozilla-firefox/9NZVDKPMR9RD)), I was able to get the token directly from [the officially recommended demo page](https://www.hcaptcha.com/privacy-pass).

![image](https://github.com/privacypass/challenge-bypass-extension/assets/9050713/6fcaae1c-fea2-4900-8928-47867d91363e)

And the fetch is amazingly fast because the addon prevents it from completing the validation, so I can validate four times in a row and then report an error.

**Comment by wordlesswind** [comment]
I don't know if this is coincidence or valid.

On Chromium, you need to allow it to pass through the Windows firewall and allow the extension to access the files, and you'll be able to get the token after restarting the browser.

There is nothing "privacy" about these operations.

**Comment by thibmeu** [comment]
hCaptcha [announced](https://www.hcaptcha.com/privacy-pass) the end of their support for the legacy Privacy Pass protocol in favor of the IETF version.

I'm closing this ticket.
